### ISSUE TITLE
Tips from MegaBlastFurnace to mislead players

### ISSUE THREAD

**Issue by KuroPeach** [GregTechCEu/gregicality-multiblocks#17]
There are 383 high-temperature smelting blocks in the tips, the minimum is 280, but according to the source code statistics, only 13 can be replaced, 13 is too few, hope to expand some. 
![image](https://user-images.githubusercontent.com/19620848/181412998-7b09f0f1-7575-415a-b8f6-1ead11a8e09e.png)
https://github.com/GregTechCEu/gregicality-multiblocks/blob/da8ababf55de68e699b05ce1a4e1cc6a1899f7f5/src/main/java/gregicality/multiblocks/common/metatileentities/multiblock/standard/MetaTileEntityMegaBlastFurnace.java#L110

**Comment by TechLord22** [comment]
I fixed the casing predicate in 6f71de0fbe44a0dafdc5df3f9f0b3f19e5751788. The effective maximum amount of hatches should be approximately 30 in the next update, which should be more than enough.
