### ISSUE TITLE
[BUG] Parlllel Control Hatch works abnormally

### ISSUE THREAD

**Issue by NaCl0526** [GregTechCEu/gregicality-multiblocks#19]
for example：
Iron ore → Crushed iron ore 2eu/t 20s
The number of parallels is set to 1 → 2eu/t 20s
The number of parallels is set to 2 → 6eu/t 20s
The number of parallels is set to 3 → 8eu/t 20s
The number of parallels is set to 128（use LV Energy Hatch） → 66eu/t 20s    The intelligent parllel control hatch thinks that 64 / 2 = 32, so it uses 32 parallelism, but it does not know that it consumes an extra energy

**Comment by PrototypeTrousers** [comment]
will be fixed by GregTechCEu/GregTech/pull/1120
The extra energy consumption is not intended.

**Comment by xeals** [comment]
I'm still observing this behaviour on v1.1.6 of GCYM and v2.5.0 of GTCEu.

Large (Thermal) Centrifuge Unit processing any crushed ore (20s @ 30EU/t) with 1 MV energy hatch (256EU/t limit):

- 1x parallel: 10s @ 120EU/t (1 overclock)
- 2x parallel: 20s @ 90EU/t (no overclock); expecting 10s @ 240EU/t 
- 3x parallel: 20s @ 120EU/t (no overclock)

In each case above 1 parallel modifier there's an extra recipe's worth in power being added.

**Comment by Mobius0526** [comment]
> I'm still observing this behaviour on v1.1.6 of GCYM and v2.5.0 of GTCEu.
> 
> Large (Thermal) Centrifuge Unit processing any crushed ore (20s @ 30EU/t) with 1 MV energy hatch (256EU/t limit):
> 
> * 1x parallel: 10s @ 120EU/t (1 overclock)
> * 2x parallel: 20s @ 90EU/t (no overclock); expecting 10s @ 240EU/t
> * 3x parallel: 20s @ 120EU/t (no overclock)
> 
> In each case above 1 parallel modifier there's an extra recipe's worth in power being added.

This issue has been closed. Your submission error may not be found
