### ISSUE TITLE
Chanced outputs do not scale and always use the lowest tier.

### ISSUE THREAD

**Issue by Targuinia** [GregTechCEu/gregicality-multiblocks#26]
Using version 1.1.5 in Nomifactory CEu  
[See this issue on the nomi-ceu repo](https://github.com/tracer4b/nomi-ceu/issues/157)

When using multiblocks on recipes with chanced outputs, such ores in the large maceration tower or large chemical bath, they will always produce chanced outputs at the lowest chance, rather than the voltage tier of the multiblock.  
As mentioned in the other issue, this happens with or without parallel hatches, and also affects processing arrays.

**Comment by TechLord22** [comment]
This should be fixed as of GTCEu v2.4.5. If this still occurs with a CEu update, please re-open this issue.
