### ISSUE TITLE
Steam Engine producing wrong amount of EU/t when dynamos beyond MV are used

### ISSUE THREAD

**Issue by Kurtchekov** [GregTechCEu/gregicality-multiblocks#32]
On version 1.1.6, the Steam Engine makes 384 EU/t if using any dynamo from HV tier and above.
As a sidenote, an observation I've made along the way: the amount of distilled water produced doesn't match the amount of distilled water needed to make the consumed steam in the first place, which renders closed loops impossible. Again, I don't know if it's intended or not so I'm adding this here as an observation instead of a full bug report of its own.

**Comment by ALongStringOfNumbers** [comment]
Should be fixed by #61
