### ISSUE TITLE
Large Fractionating Distillery requires a maintenance hatch when maintenance is disabled

### ISSUE THREAD

**Issue by pyure** [GregTechCEu/gregicality-multiblocks#39]
When I attempt to construct a Large Fractionating Distillery, the structure will not form unless I include a Maintenance hatch.  This should not be the case if Maintenance is disabled via configs.

* v.1.1.6  (GT 2.5.2-beta)
* Identified with Large Fractionating Distillery.
* Confirmed world had restarted since Maintenance had been disabled via in-game config
* Confirmed LCR **does** build w/o a maintenance hatch when maintenance is disabled

Workarounds:
* Include a Maintenance hatch, then disable Maintenance.

**Comment by TechLord22** [comment]
Should be fixed with 84e8a7d.
