### ISSUE TITLE
Certain Alloy Blast Smelter auto-recipes not generating

### ISSUE THREAD

**Issue by m2r1k5** [GregTechCEu/gregicality-multiblocks#4]
Certain ABS auto-recipes don't generate despite them meeting the criteria of having 2 or more components and being made in the EBF.
They include vanilla CEu alloys such as Ruridit and Naquadah Alloy, as well as certain CT-generated materials such as 
![image](https://user-images.githubusercontent.com/61507029/152631520-a6b3b2e4-6659-4073-8387-fcfc1147cd86.png)

**Comment by TechLord22** [comment]
This should be fixed as of c1275d7, which will be in the next release of GCYM. It depends on a GTCEu update not yet released, so until then I'll leave this issue open.
