### ISSUE TITLE
some issues of ABS

### ISSUE THREAD

**Issue by Namacack** [GregTechCEu/gregicality-multiblocks#41]
1.Indium Tin Barium Titanium Cuprate is produced in higher yields in ABS than Mixer
2.Molten Ruridit's recipe is gone

Edit:Molten Ruridit itself was gone

**Comment by IntegerLimit** [comment]
ABS?

**Comment by Namacack** [comment]
it's a typo sorry

**Comment by TechLord22** [comment]
This is resolved as of d47d87378fdbda1972276c39eab006378634106a, so I am closing this issue.
