### ISSUE TITLE
no bus isolation mode for large wiremill 

### ISSUE THREAD

**Issue by huanyuehjj** [GregTechCEu/gregicality-multiblocks#45]
In gtceu version 2.6.0, different circuit recipes exist for wiremill, but there is no bus isolation mode for large wiremill.

**Comment by TechLord22** [comment]
Resolved as of #44.

**Comment by huanyuehjj** [comment]
sorry，I didn't look closely at these issues。

**Comment by huanyuehjj** [comment]
Will he be added in the next update?

**Comment by TechLord22** [comment]
Yes, it will be present in the upcoming update.
