### ISSUE TITLE
ABS recipes for materials without hot ingots (aka non-molten ABS recipes) are no longer generated in 1.2.2

### ISSUE THREAD

**Issue by IntegerLimit** [GregTechCEu/gregicality-multiblocks#47]
Title. This is probably due to https://github.com/GregTechCEu/gregicality-multiblocks/blob/master/src/main/java/gregicality/multiblocks/api/AlloyBlastUtil.java#L24 erroring, although, I really don't have any idea.

Check materials such as Vanadium Steel, Blue Steel, Red Steel and Black Steel. They have ABS recipes in GCYM 1.2.1, but those recipes disappear in 1.2.2. Same problem applies to custom CT materials, and probably applies to groovy materials too.

**Comment by TechLord22** [comment]
Fixed as of 94655d32bf7d0c8c92a1cb7a74874a787dd534ea. A test has additionally been added to help prevent these issues in the future as well.
