### ISSUE TITLE
multiblock structures don't form with laser target hatches

### ISSUE THREAD

**Issue by FaccoCris** [GregTechCEu/gregicality-multiblocks#70]
Hello this happened on Nomi CEu Version 1.7-alpha-3

Only mod added is Fluid Craft for AE2 version 2.5.6

This happened on a multiplayer Forge server.

What Happened:

Building the circuit assembler multiblock using the target hatch as seen here
![331820037-3fd12919-ebf8-4147-b94c-8da78527aa5e](https://github.com/GregTechCEu/gregicality-multiblocks/assets/73462627/fdf71989-f552-45f1-a80e-097a738221ba)
the multiblock still doesn't form and the controller still reads structure incomplete
![331820085-58d0f8a3-21f3-4980-a12b-2df9ca1e6974](https://github.com/GregTechCEu/gregicality-multiblocks/assets/73462627/2521975a-e402-4a46-8c75-cd68c7f0a0fa)
of course the hatch is properly connected on the underside
![2024-05-19_12 19 23](https://github.com/GregTechCEu/gregicality-multiblocks/assets/73462627/0f250c9b-223d-4942-86ce-752f4f0f7990)

Expected Behavior
As i interpret the description of the block as seen here
![2024-05-19_12 17 44](https://github.com/GregTechCEu/gregicality-multiblocks/assets/73462627/fe8b668b-5619-4fc4-91e6-0ddc1c3c2df4)
The multiblock should've accepted the laser target hatch as an acceptable energy hatch and formed the structure correctly.

**Comment by ghzdude** [comment]
Large Multiblocks only accept energy hatches, this is intentional. iirc, it's planned to allow the Rotary Hearth Furnace and Bulk Blast Chiller to accept laser target hatches.

**Comment by FaccoCris** [comment]
can you explain what the multiblock sharing tag in the description means then? thanks in advance

**Comment by ghzdude** [comment]
It means that the hatch or bus can be shared between several multiblocks when you wall-share them (overlapping the walls of similar multiblocks with each other)

**Comment by FaccoCris** [comment]
but only if the multiblocks are the rotary furnace or the bulk blast chiller, i see.... :(
