### ISSUE TITLE
1.2.10 Recipemap doesn't show up in HEI

### ISSUE THREAD

**Issue by Frosteco** [GregTechCEu/gregicality-multiblocks#72]
Recipes utilizing GTCEu recipemap (assemblers, centrifuges - all of gtceu and gregicality machines) don't show up in HEI
crafting table recipes still show up
gregicality 1.2.9 doesn't have this issue

Modlist
gregicality multiblocks 1.2.10
had enough items 4.25.5
gregtech CE Unoficial 2.8.10 beta
codechickenlib 3.2.3.358 universal

**Comment by TechLord22** [comment]
Fixed by #74.
