### ISSUE TITLE
[Suggestion] Multiblock for the Alloy Smelter single block

### ISSUE THREAD

**Issue by Dyonovan** [GregTechCEu/gregicality-multiblocks#78]
It seems that almost all single block machines have a multiblock alternative. Just seems wierd to not have one for the Alloy Smelter.

**Comment by ghzdude** [comment]
All recipes involving metal alloys from the Alloy Smelter are already added to the Alloy Blast Smelter multiblock. Alloy Smelter recipes involving a mold intentionally do not have a multiblock to run them.

**Comment by Dyonovan** [comment]
So things like the Micro Miner Engine Cores do not have multiblock equivalent and this is intentional?

**Comment by ghzdude** [comment]
That is a recipe that is added by a modpack, and it's the modpack maker's responsibility to add that to a multiblock

**Comment by Dyonovan** [comment]
Ok. Thanks for the info.
